project:
  type: book

book:
  title: "R pour ma grand-mère"
  author: "Vincent Bonhomme"
  date: "04/13/2024"
  chapters:
    - index.qmd
    - install.qmd
    - 3min-tour.qmd
    - premiers-pas.qmd
    - programmation.qmd
    - modelling.qmd
    - magrittr.qmd
    - import.qmd
    - dplyr.qmd
    - tidyr.qmd
    - ggplot2.qmd
    - purrr.qmd
    - tidyrest.qmd
    - vocabulaire.qmd
    - ressources.qmd
  repo-url: https://www.rstudio.com/   
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf, epub]

    
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-expand: 3
    include-after-body: footer.html
    toc-title: "Dans ce chapitre"
    highlight-style: github
    code-link: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

  pdf:
    documentclass: scrreprt

editor: source

execute:
  freeze: auto
  
