# Préface {.unnumbered}

## À propos de l'ouvrage
La vocation de cet ouvrage est de fournir un point de départ rapide mais solide aux principaux usages de R, un environnement complet et open-source pour l'analyse de données.

L'auteur a tenté d'écrire la ressource qu'il aurait aimé avoir à ses débuts, dans l'esprit de ses deux références chéries : [_R pour les débutants_](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_fr) d'Emmanuel Paradis et [_R for data science_](https://r4ds.hadley.nz/) d'Hadley Wichkam. Une sélection de références plus complètes et/ou plus spécifiques, sont listées.

Il sert de compagnon à une formation pour des absolu·e·s débutant·e·s sur une durée présentielle de 3 jours (18h). Son intention est d'autonomiser ces utilisateur·trice·s tout en espérant être utiles aux non-néophytes voire aux plus assidu·e·s.

Le titre est un hommage à ma grand-mère, certes plus intarissable sur la sociologie provençale des années 1950 que sur la coercion de classe à la volée.

## À propos de l'auteur

Je suis biologiste de l'évolution de formation et aujourd'hui consultant, formateur et chercheur associé à l'UMR ISEM à Montpellier. J'utilise R quotidiennement depuis 2006 et je suis l'auteur de nombreux packages dont [Momocs](https://github.com/MomX/Momocs), pour l'analyse de forme.

Je suis disponible pour de la consultance et des formations sur à peu près tous les "niveaux" d'utilisation de R, depuis le tout début jusqu'au packaging et la contruction d'interface conviviales ala shiny.

En *side project*, j'ai confondé [Cévennette](https://www.cevennette.fr) qui conçoit et fabrique des toilettes sèches à séparation, sans odeur et sans copeaux, pour les particuliers, les événements et les collectivités.

Si vous avez envie de faire pipi ou si vous cherchez un formateur ou un consultant en R, voici mes contacts :

-   [www.vincentbonhomme.fr](https://www.vincentbonhomme.fr)
-   [bonhomme.vincent\@gmail.com](mailto:bonhomme.vincent\@gmail.com)

## Code source
* Si vous le lisez en pdf, il est disponible en ligne ici : [https://vbonhomme.github.io/R-pour-ma-grand-mere]().
* Si vous le lisez en ligne, il est disponible en pdf [ici](https://github.com/vbonhomme/R-pour-ma-grand-mere/blob/main/_book/R-pour-ma-grand-m%C3%A8re.pdf)
* Ce document Quarto est écrit en Rmarkdown et hébergé par Github: [https://github.com/vbonhomme/R-pour-ma-grand-mere]
* Si vous êtes à l'aise sur Github, vous pouvez directement modifier le contenu que j'approuverai (ou non), pour corriger une erreur, une coquille, etc. Si vous souhaitez simplement suggérer une modification ou signaler un problème, vous pouvez très simplement ouvrir un "ticket" dans l'onglet "Issues".

## Licence
Ce document est placé par l'auteur sous licence CC0, ce qui signifie que vous pouvez en faire absolument ce que vous voulez, sans me demander quoique ce soit. Naturellement, me citer est néanmoins bon pour votre karma !

## Conventions

Le code en ligne utilisera ```une police de ce type```; les blocs ressemblent à celui ci :

```{r}
# this is a comment
3+4
```

Généralement, le résultat s'affiche à proximité et vous pouvez copier-coller ce code dans R (ou cliquer sur le bouton en haut à droite du cadre) et obtenir le même résultat sur votre machine.
Tout ce qui suit un `#` est un commentaire - lisez-les ! - et est ignoré par R.

Parfois, une maxime de sagesse populaiRe est insérée dans un bloc comme ci-dessous. Promis, elles ne réfèrent pas toutes au sous-vêtements.

> Les statistiques sont comme les petites culottes : elles montrent le superflu et cachent l'essentiel.

----






