name: R-CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v3

      # 2️⃣ Installer R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      # 3️⃣ Installer les dépendances système nécessaires
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev \
                                  libgit2-dev build-essential r-base-dev

      # 4️⃣ Installer renv si nécessaire
      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      # 5️⃣ Restaurer les packages R depuis renv.lock
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Restore renv environment
        run: Rscript -e 'renv::restore()'

      # 6️⃣ Tester le projet (optionnel)
      - name: Run tests
        run: Rscript -e 'if (requireNamespace("devtools")) devtools::test()'
