name: R-CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code
      - uses: actions/checkout@v3

      # 2️⃣ Installer R 4.5.1
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      # 3️⃣ Installer les dépendances système pour compiler les packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev \
                                  libgit2-dev build-essential r-base-dev

      # 4️⃣ Installer renv si nécessaire
      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      # 5️⃣ Forcer renv à utiliser la version du projet
      - name: Align renv version
        run: Rscript -e 'renv::record("renv@1.1.5"); renv::snapshot()'

      # 6️⃣ Cache des packages R pour accélérer la CI
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-R-

      # 7️⃣ Restaurer l’environnement renv
      - name: Restore renv environment
        run: Rscript -e 'renv::restore()'
